###
GET https://localhost:5001/test/johan

###

PUT https://localhost:5001/test/johan
Content-Type: application/json

{
    "hello": "Johan"
}

###
GET http://localhost/test/johan

###

PUT http://localhost/test/johan
Content-Type: application/json

{
    "hello": "Johan"
}

###

GET http://localhost:5000/test/johan

###

PUT http://localhost:5000/test/johan
Content-Type: application/json

{
    "hello": "Running in Kubernetes"
}

###

GET https://jsonbase.izaxon.com/test/johan

###

PUT https://jsonbase.izaxon.com/test/johan
Content-Type: application/json

{
    "hello": "Running on the internet"
}

###

POST http://localhost:5000/test/johan
Content-Type: application/json

{
    "hello3": "Running on PC"
}

###

GET http://localhost:5000/test/johan3

###

PUT http://localhost:5000/test/johan3
Content-Type: application/json

["1","2","3", "4"]

###

POST http://localhost:5000/test/johan3
Content-Type: application/json

["11","22"]

###
