###
GET https://localhost:5001/test/johan

###

PUT https://localhost:5001/test/johan
Content-Type: application/json

{
    "hello": "Johan"
}

###
GET http://localhost/test/johan

###

PUT http://localhost/test/johan
Content-Type: application/json

{
    "hello": "Johan"
}

###

GET http://localhost:4000/test/johan

###

PUT http://localhost:4000/test/johan
Content-Type: application/json

{
    "hello": "Running in Kubernetes"
}

###

GET https://jsonbase.izaxon.com/test/johan

###

PUT https://jsonbase.izaxon.com/test/johan
Content-Type: application/json

{
    "hello": "Running on the internet"
}